<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Failed suite [Failed suite [Failed suite [Suite]]]]" duration-ms="164" started-at="2022-05-28T18:46:29Z" finished-at="2022-05-28T18:46:29Z">
    <groups>
    </groups>
    <test name="Test(failed)(failed)(failed)(failed)" duration-ms="164" started-at="2022-05-28T18:46:29Z" finished-at="2022-05-28T18:46:29Z">
      <class name="maven_surefire_compile_plugins.RegisterUser">
        <test-method status="FAIL" signature="enterUserDetails()[pri:0, instance:maven_surefire_compile_plugins.RegisterUser@735b5592]" name="enterUserDetails" duration-ms="111" started-at="2022-05-28T18:46:29Z" finished-at="2022-05-28T18:46:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed purposely using Assert Fail]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed purposely using Assert Fail
at org.testng.Assert.fail(Assert.java:96)
at maven_surefire_compile_plugins.RegisterUser.enterUserDetails(RegisterUser.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterUserDetails -->
      </class> <!-- maven_surefire_compile_plugins.RegisterUser -->
    </test> <!-- Test(failed)(failed)(failed)(failed) -->
  </suite> <!-- Failed suite [Failed suite [Failed suite [Failed suite [Suite]]]] -->
</testng-results>
